### ISSUE TITLE
Remove time sleep (or change)

### ISSUE THREAD

**Issue by loonydev** [tezer/OppiWordsBot#8]
If user have 1k words, he must wait 1k*0.5 = 500 secs, it's almost 10 minutes. For what? Why it's 0.5 sec? Why you need to sleep, if previous call was with `await`?
https://github.com/tezer/OppiWordsBot/blob/744175d13f608ad5033e766db8fd36cf55c4f87b/oppi_wiki_bot.py#L185

**Comment by tezer** [comment]
Telegram may block the bot for frequent messages

**Comment by loonydev** [comment]
Okay, sound logical.
